### PR TITLE
Move to .NET 6

### PR DESCRIPTION
**Pull request by sitiom**
.NET Framework is deprecated, and .NET 6 is the way forward (Also comes with performance improvements).

Also, can you provide a portable version of the application? Seeing that the app is quite small, a portable version would make sense.

Edit: Updated for .NET 6

### CODE REVIEW

**Comment by sitiom** [comment]
@ktheod Why is this closed?

**Comment by ktheod** [comment]
Hi Sitiom, Sorry I probably closed it by mistake when releasing 1.4. 
I agree with the request, when I have a bit free time from work, I will upgrade the solution to use the latest .Net version.
This will be in release 1.5. I will update you here when this is done (expecting in the following weeks as it is probably a minor change).

Regarding having a portable version, you can copy the OneDrive Bully folder (includes the .exe and .ico files) to any folder or other computer. After copying, run it as Admin to set the settings and from there on you can have it running on Windows Startup etc. 

The msi really is just an installer to create the start menu, folder and copy the files there. Doesn't do much else. 

Thanks,

**Comment by ktheod** [comment]
Note for me: Add it on Version 1.5

**Comment by ktheod** [comment]
Note for me: Add it on Version 1.5

**Pull request closed without merging**
